# Generated by Django 3.0.7 on 2020-08-02 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=30)),
                ('landmark', models.CharField(default=None, max_length=80)),
                ('address1', models.TextField(max_length=100)),
                ('address2', models.TextField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('zipcode', models.IntegerField()),
                ('rent', models.IntegerField()),
                ('rentedby', models.IntegerField(blank=True, null=True)),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
