# Generated by Django 3.0.7 on 2020-08-02 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='rentedby',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
